version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
  backend:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./env
    ports:
      - $PORT:$PORT
    environment:
      - MONGO_HOST = mongodb
      - MONGO_PORT = 27017
      - MONGO_USER =
      - MONGO_PASS =
      - MONGO_NAME = db_auth_token_refresh
      - PORT = 8080
      - SALT = 10
      - ACCESS_TOKEN_PRIVATE_KEY = my-secret
      - REFRESH_TOKEN_PRIVATE_KEY = my-secret
    stdin_open: true
    tty: true
volumes: 
  db: